spring:
  datasource:
    url: jdbc:mysql://localhost:3306/artloc?serverTimeZone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
#      use-new-id-generator-mappings: false
    show-sql: true